import type { CharacterData } from "../types/character";

const breakinBadCharacters: CharacterData[] = [
  {
    id: 1,
    name: "Walter White",
    nickname: "Heisenberg",
    occupation: ["High School Chemistry Teacher", "Meth Kingpin"],
    status: "Deceased",
    img: "https://i.pinimg.com/564x/fc/db/84/fcdb8412f5f8f52c73a7d167bd3e3da4.jpg",
  },
  {
    id: 2,
    name: "Jesse Pinkman",
    nickname: "Cap n' Cook",
    occupation: ["Meth Manufacturer"],
    status: "Alive",
    img: "https://i.pinimg.com/564x/3b/e1/d2/3be1d212d91df28b13f6ebb04d51b7ed.jpg",
  },
  {
    id: 3,
    name: "Skyler White",
    nickname: "Sky",
    occupation: ["Accountant"],
    status: "Alive",
    img: "https://i.pinimg.com/564x/af/59/4e/af594ec1c8a5339f1a3182c2b75a79ae.jpg",
  },
  {
    id: 4,
    name: "Hank Schrader",
    nickname: "ASAC Schrader",
    occupation: ["DEA Agent"],
    status: "Deceased",
    img: "https://i.pinimg.com/564x/be/56/d0/be56d06993c0d08001c8ae0cb6b03cbe.jpg",
  },
  {
    id: 5,
    name: "Saul Goodman",
    nickname: "Goodman",
    occupation: ["Lawyer"],
    status: "Alive",
    img: "https://i.pinimg.com/564x/c8/8a/c3/c88ac3d2cce05c184e652f341ffc5af4.jpg",
  },
  {
    id: 6,
    name: "Gus Fring",
    nickname: "The Chicken Man",
    occupation: ["Los Pollos Hermanos Owner", "Meth Distributor"],
    status: "Deceased",
    img: "https://i.pinimg.com/564x/71/c3/64/71c3646ae8158efa14ff5315a9995125.jpg",
  },
  {
    id: 7,
    name: "Mike Ehrmantraut",
    nickname: "Mike",
    occupation: ["Fixer", "Private Investigator"],
    status: "Deceased",
    img: "https://i.pinimg.com/736x/16/6e/62/166e62151fbb08e3c1f1daa636224db7.jpg",
  },
  {
    id: 8,
    name: "Marie Schrader",
    nickname: "Marie",
    occupation: ["Radiologic Technologist"],
    status: "Alive",
    img: "https://i.pinimg.com/564x/5c/5d/87/5c5d875eb5810965a9d6748c16911d2f.jpg",
  },
  {
    id: 9,
    name: "Todd Alquist",
    nickname: "Ricky Hitler",
    occupation: ["Lab Assistant", "Enforcer"],
    status: "Deceased",
    img: "https://i.pinimg.com/564x/3a/be/91/3abe91936ebab5f0ecd0818ed8da08c9.jpg",
  },
  {
    id: 10,
    name: "Lydia Rodarte-Quayle",
    nickname: "Lydia",
    occupation: ["Logistics Coordinator", "Meth Distributor"],
    status: "Deceased",
    img: "https://i.pinimg.com/564x/84/af/94/84af94ee7ed5f7d5d7d6d55cb2489c82.jpg",
  },
  {
    id: 11,
    name: "Jane Margolis",
    nickname: "Jane",
    occupation: ["Tattoo Artist"],
    status: "Deceased",
    img: "https://i.pinimg.com/564x/cf/c0/a3/cfc0a3a104b8fe80088397c4314814aa.jpg",
  },
  {
    id: 12,
    name: "Tuco Salamanca",
    nickname: "Tuco",
    occupation: ["Drug Dealer"],
    status: "Deceased",
    img: "https://www.breakingbadapi.com/api/characters/12/image",
  },
  {
    id: 13,
    name: "Hector Salamanca",
    nickname: "Tio",
    occupation: ["Enforcer", "Cartel Associate"],
    status: "Deceased",
    img: "https://www.breakingbadapi.com/api/characters/13/image",
  },
  {
    id: 14,
    name: "Victor",
    nickname: "Victor",
    occupation: ["Gus' Enforcer"],
    status: "Deceased",
    img: "https://www.breakingbadapi.com/api/characters/14/image",
  },
  {
    id: 15,
    name: "Gale Boetticher",
    nickname: "Gale",
    occupation: ["Chemist"],
    status: "Deceased",
    img: "https://www.breakingbadapi.com/api/characters/15/image",
  },
  {
    id: 16,
    name: "Steven Gomez",
    nickname: "Gomie",
    occupation: ["DEA Agent"],
    status: "Deceased",
    img: "https://www.breakingbadapi.com/api/characters/16/image",
  },
  {
    id: 17,
    name: "Combo Ortega",
    nickname: "Combo",
    occupation: ["Drug Dealer"],
    status: "Deceased",
    img: "https://www.breakingbadapi.com/api/characters/17/image",
  },
  {
    id: 18,
    name: "Skinny Pete",
    nickname: "Skinny",
    occupation: ["Drug Dealer"],
    status: "Alive",
    img: "https://www.breakingbadapi.com/api/characters/18/image",
  },
  {
    id: 19,
    name: "Badger",
    nickname: "Badger",
    occupation: ["Drug Dealer"],
    status: "Alive",
    img: "https://www.breakingbadapi.com/api/characters/19/image",
  },
  {
    id: 20,
    name: "Krazy-8",
    nickname: "Krazy-8",
    occupation: ["Drug Dealer"],
    status: "Deceased",
    img: "https://www.breakingbadapi.com/api/characters/20/image",
  },
];

export default breakinBadCharacters;
